import 'dart:async';
import 'dart:convert';
import 'dart:math';
import 'package:archive/archive.dart';
import 'package:crypto/crypto.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shadcn_ui/shadcn_ui.dart';
import 'package:video_player/video_player.dart';
import 'package:zhiyue_client/core/api_client.dart';
import 'package:zhiyue_client/core/api_contract.dart';
import 'package:zhiyue_client/core/api_response.dart';
import 'package:zhiyue_client/core/api_transport_io.dart';
import 'package:zhiyue_client/core/cloud_id_signer.dart';
import 'package:zhiyue_client/core/comment_emoticon_assets.dart';
import 'package:zhiyue_client/core/comment_link.dart';
import 'package:zhiyue_client/core/content_filter_stats.dart';
import 'package:zhiyue_client/core/follow_item_group.dart';
import 'package:zhiyue_client/core/json_tools.dart';
import 'package:zhiyue_client/core/mobile_login_body_encoder.dart';
import 'package:zhiyue_client/core/mobile_login_contract.dart';
import 'package:zhiyue_client/core/negative_feedback.dart';
import 'package:zhiyue_client/core/input_validation.dart';
import 'package:zhiyue_client/core/privacy_device_profile.dart';
import 'package:zhiyue_client/core/recommendation_engine.dart';
import 'package:zhiyue_client/core/session_store.dart';
import 'package:zhiyue_client/core/salt_bookshelf_store.dart';
import 'package:zhiyue_client/core/salt_catalog_store.dart';
import 'package:zhiyue_client/core/salt_chapter_cache.dart';
import 'package:zhiyue_client/core/salt_chapter_export.dart';
import 'package:zhiyue_client/core/salt_manuscript_key.dart';
import 'package:zhiyue_client/core/salt_reader_adapter.dart';
import 'package:zhiyue_client/core/salt_text_chapter.dart';
import 'package:zhiyue_client/core/salt_transport_decoder.dart';
import 'package:zhiyue_client/core/x_zse_signer.dart';
import 'package:zhiyue_client/main.dart' as app;
import 'package:zhiyue_client/pages/account_page.dart';
import 'package:zhiyue_client/pages/account_profile_pages.dart';
import 'package:zhiyue_client/pages/web_page.dart';
import 'package:zhiyue_client/pages/browsing_history_page.dart';
import 'package:zhiyue_client/pages/native_login_page.dart';
import 'package:zhiyue_client/pages/notifications_page.dart';
import 'package:zhiyue_client/pages/content_pages.dart';
import 'package:zhiyue_client/pages/feed_page.dart';
import 'package:zhiyue_client/pages/my_page.dart';
import 'package:zhiyue_client/pages/paged_list_page.dart';
import 'package:zhiyue_client/pages/salt_page.dart';
import 'package:zhiyue_client/pages/search_page.dart';
import 'package:zhiyue_client/pages/user_page.dart';
import 'package:zhiyue_client/ui/zh_components.dart';
import 'package:zhiyue_client/ui/zh_theme.dart';
import 'package:zhiyue_client/widgets/app_drawer.dart';
import 'package:zhiyue_client/widgets/api_views.dart';
import 'package:zhiyue_client/widgets/comment_composer_sheet.dart';
import 'package:zhiyue_client/widgets/negative_feedback_sheet.dart';
import 'package:zhiyue_client/widgets/salt_chapter_view.dart';

import 'fixtures/salt_laes_vectors.dart';

part 'core_test_parts/salt_core_tests.dart';
part 'core_test_parts/account_shell_tests.dart';
part 'core_test_parts/content_feed_tests.dart';
part 'core_test_parts/feed_salt_widget_tests.dart';
part 'core_test_parts/salt_model_tests.dart';
part 'core_test_parts/detail_comment_tests.dart';
part 'core_test_parts/comment_composer_tests.dart';
part 'core_test_parts/search_session_tests.dart';
part 'core_test_parts/login_signature_tests.dart';
part 'core_test_parts/api_profile_tests.dart';
part 'core_test_parts/negative_feedback_tests.dart';
part 'core_test_parts/second_priority_tests.dart';
part 'core_test_parts/test_support.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  registerSaltCoreTests();
  registerAccountShellTests();
  registerContentFeedTests();
  registerFeedSaltWidgetTests();
  registerSaltModelTests();
  registerDetailCommentTests();
  registerCommentComposerTests();
  registerSearchSessionTests();
  registerLoginSignatureTests();
  registerApiProfileTests();
  registerNegativeFeedbackTests();
  registerSecondPriorityTests();
}
